<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.giss.com.br/consultar-nota-servico-comprado-envio-v1_00.xsd"
    xmlns="http://www.giss.com.br/consultar-nota-servico-comprado-envio-v1_00.xsd"
    xmlns:dsig="http://www.w3.org/2000/09/xmldsig#"
    xmlns:tipos1="http://www.giss.com.br/tipos-servicos-comprados-v1_00.xsd"
    attributeFormDefault="unqualified"
    elementFormDefault="qualified">

    <xsd:import
        namespace="http://www.giss.com.br/tipos-servicos-comprados-v1_00.xsd"
        schemaLocation="tipos-servicos-comprados-v1_00.xsd" />
        
    <xsd:import namespace="http://www.w3.org/2000/09/xmldsig#"
        schemaLocation="xmldsig-core-schema20020212.xsd" />       

    <xsd:element name="ConsultarServicoCompradoPorNumeroEnvio">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element
                    name="Tomador"
                    type="tipos1:IdentificacaoPessoaEmpresa" />
                <xsd:element
                    name="NumeroDeclarado"
                    type="xsd:nonNegativeInteger" minOccurs="0" maxOccurs="1"/>
                <xsd:element name="SerieDeclarada" type="xsd:string" minOccurs="0" maxOccurs="1"/>
                <xsd:element
                    name="PeriodoCompetencia"
                    type="tipos1:PeriodoCompetencia" />
                <xsd:element
                    name="PeriodoEmissao"
                    type="tipos1:PeriodoCompetencia" />
                <xsd:element ref="dsig:Signature" minOccurs="0" maxOccurs="1" />       
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>
